name: Build Windows EXE

on:
  push:
    branches:
      - main # Run on pushes to the main branch
  workflow_dispatch: # Allow manual triggering

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3' # Specify Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PyInstaller
        run: pyinstaller --onefile --windowed --name converter --icon src/converter_tools/assets/icons/app_icon.ico --add-data "src/converter_tools/assets:converter_tools/assets" --add-data "src/converter_tools/converter_settings.json:converter_tools" src/converter.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: converter-windows-exe
          path: dist/converter.exe # Path to the generated EXE
